version: '3.8'

services:
  app-blue:
    build: ..
    container_name: app-blue
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    command: sh -c "node src/index.js"

  app-green:
    build: ..
    container_name: app-green
    environment:
      - PORT=3002
    ports:
      - "3002:3002"
    command: sh -c "node src/index.js"

  reverse-proxy:
    image: node:18-alpine
    container_name: router
    working_dir: /app
    volumes:
      - ./router:/app
    command: ["node", "router.js"]
    ports:
      - "8090:3000"       # host port here (host:container)
    environment:
      - CANARY_PERCENT=20  # Adjust canary traffic here (default 10% to 20%)
    depends_on:
      - app-blue
      - app-green

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../infra/monitoring/prometheus-config.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3005:3000"
    volumes:
      - ../infra/monitoring/grafana-dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_DASHBOARDS_JSON_ENABLED=true
      - GF_DASHBOARDS_JSON_PATH=/var/lib/grafana/dashboards
